# Generated by Django 5.1 on 2024-08-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialsite', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='icons/profileicon.jpeg', null=True, upload_to=''),
        ),
    ]
